### ISSUE TITLE
app crashs because of os bar

### ISSUE THREAD

**Issue by peterandree** [mindsphere/start-for-free-demo-app#1]
I used the app with my eu1 tenant. I nabbed the cookies from my sdk app with all kind of rights (I believe that shouldnt make a difference,  but anyway) and started the proxy.

I get the following error:

Proxy error: Could not proxy request /api/tenantmanagement/v4/tenantInfo/logo from localhost:3000 to http://localhost:7707/.
See https://nodejs.org/api/errors.html#errors_common_system_errors for more information (HPE_INVALID_CONSTANT).

events.js:291
      throw er; // Unhandled 'error' event
      ^

Error [ERR_STREAM_WRITE_AFTER_END]: write after end
    at write_ (_http_outgoing.js:641:17)
    at ServerResponse.write (_http_outgoing.js:633:15)
    at ServerResponse.write (D:\projects\start-for-free-demo-app-master\node_modules\compression\index.js:89:18)
    at IncomingMessage.ondata (_stream_readable.js:718:22)
    at IncomingMessage.emit (events.js:314:20)
    at IncomingMessage.Readable.read (_stream_readable.js:507:10)
    at flow (_stream_readable.js:1007:34)
    at resume_ (_stream_readable.js:988:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
Emitted 'error' event on ServerResponse instance at:
    at writeAfterEndNT (_http_outgoing.js:696:7)
    at processTicksAndRejections (internal/process/task_queues.js:85:21) {
  code: 'ERR_STREAM_WRITE_AFTER_END'
}

The issue can be solved by commenting out the os bar. I would assume this is an issue with the os bar, but maybe it should be commented out in the source to avoid frustration.

**Comment by sn0wcat** [comment]
@peterandree  this is an issue with /v4/tenantinfo/logo , can u remove the logo from your tenant and try again?

**Comment by peterandree** [comment]
os bar works without the logo
